// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SkipperData.Data;

#nullable disable

namespace SkipperData.Migrations
{
    [DbContext(typeof(SkipperContext))]
    [Migration("20250806155535_Orders-Customers-TPH")]
    partial class OrdersCustomersTPH
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("skipper")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SkipperModels.Entities.AddressEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .UseCollation("en-US-x-icu");

                    b.Property<string>("Address2")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .UseCollation("en-US-x-icu");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .UseCollation("en-US-x-icu");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .UseCollation("en-US-x-icu");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .UseCollation("en-US-x-icu");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .UseCollation("en-US-x-icu");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("addresses", "skipper");
                });

            modelBuilder.Entity("SkipperModels.Entities.BusinessCustomerContactsEntity", b =>
                {
                    b.Property<long>("BusinessCustomerId")
                        .HasColumnType("bigint");

                    b.Property<long>("ContactId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEmergency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BusinessCustomerId", "ContactId");

                    b.HasIndex("ContactId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("business_customer_contacts", "skipper");
                });

            modelBuilder.Entity("SkipperModels.Entities.ContactEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .UseCollation("en-US-x-icu");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .UseCollation("en-US-x-icu");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .UseCollation("en-US-x-icu");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .UseCollation("en-US-x-icu");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("contacts", "skipper");
                });

            modelBuilder.Entity("SkipperModels.Entities.CustomerEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .UseCollation("en-US-x-icu");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerProfileType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .UseCollation("en-US-x-icu");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.ToTable("customers", "skipper");

                    b.HasDiscriminator<int>("CustomerProfileType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SkipperModels.Entities.OrderEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .UseCollation("en-US-x-icu");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .UseCollation("en-US-x-icu");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("OrderType");

                    b.HasIndex("Status", "OrderDate");

                    b.ToTable("orders", "skipper");

                    b.HasDiscriminator<string>("OrderType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SkipperModels.Entities.SlipClassificationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BasePrice")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("en-US-x-icu");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("MaxBeam")
                        .HasPrecision(19, 5)
                        .HasColumnType("numeric(19,5)");

                    b.Property<decimal>("MaxLength")
                        .HasPrecision(19, 5)
                        .HasColumnType("numeric(19,5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .UseCollation("en-US-x-icu");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BasePrice");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name");

                    b.ToTable("slip_classifications", "skipper");
                });

            modelBuilder.Entity("SkipperModels.Entities.SlipEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .UseCollation("en-US-x-icu");

                    b.Property<long>("SlipClassificationId")
                        .HasColumnType("bigint");

                    b.Property<string>("SlipNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .UseCollation("en-US-x-icu");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SlipClassificationId");

                    b.HasIndex("SlipNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("slips", "skipper");
                });

            modelBuilder.Entity("SkipperModels.Entities.VesselEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Beam")
                        .HasPrecision(19, 5)
                        .HasColumnType("numeric(19,5)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Length")
                        .HasPrecision(19, 5)
                        .HasColumnType("numeric(19,5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .UseCollation("en-US-x-icu");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .UseCollation("en-US-x-icu");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VesselType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.HasIndex("VesselType");

                    b.ToTable("vessels", "skipper");
                });

            modelBuilder.Entity("SkipperModels.Entities.VesselOwnerVesselEntity", b =>
                {
                    b.Property<long>("VesselOwnerCustomerId")
                        .HasColumnType("bigint");

                    b.Property<long>("VesselId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("VesselOwnerCustomerId", "VesselId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("VesselId")
                        .IsUnique();

                    b.ToTable("vessel_owner_vessels", "skipper");
                });

            modelBuilder.Entity("SkipperModels.Entities.BusinessCustomerEntity", b =>
                {
                    b.HasBaseType("SkipperModels.Entities.CustomerEntity");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .UseCollation("en-US-x-icu");

                    b.Property<string>("TaxId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .UseCollation("en-US-x-icu");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("SkipperModels.Entities.IndividualCustomerEntity", b =>
                {
                    b.HasBaseType("SkipperModels.Entities.CustomerEntity");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreferredContactMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .UseCollation("en-US-x-icu");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("SkipperModels.Entities.MemberCustomerEntity", b =>
                {
                    b.HasBaseType("SkipperModels.Entities.CustomerEntity");

                    b.Property<DateTime?>("MemberSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MembershipLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .UseCollation("en-US-x-icu");

                    b.Property<string>("MembershipNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .UseCollation("en-US-x-icu");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("SkipperModels.Entities.VesselOwnerCustomerEntity", b =>
                {
                    b.HasBaseType("SkipperModels.Entities.CustomerEntity");

                    b.Property<long>("ContactId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LicenseExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .UseCollation("en-US-x-icu");

                    b.HasIndex("ContactId");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("SkipperModels.Entities.SlipReservationOrderEntity", b =>
                {
                    b.HasBaseType("SkipperModels.Entities.OrderEntity");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PriceRate")
                        .HasColumnType("integer");

                    b.Property<string>("PriceUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RentalStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SlipId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("VesselId")
                        .HasColumnType("bigint");

                    b.HasIndex("RentalStatus");

                    b.HasIndex("SlipId");

                    b.HasIndex("VesselId");

                    b.HasIndex("SlipId", "StartDate", "EndDate");

                    b.HasDiscriminator().HasValue("SlipReservation");
                });

            modelBuilder.Entity("SkipperModels.Entities.BusinessCustomerContactsEntity", b =>
                {
                    b.HasOne("SkipperModels.Entities.BusinessCustomerEntity", "BusinessCustomer")
                        .WithMany("BusinessCustomerContacts")
                        .HasForeignKey("BusinessCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkipperModels.Entities.ContactEntity", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessCustomer");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("SkipperModels.Entities.ContactEntity", b =>
                {
                    b.HasOne("SkipperModels.Entities.AddressEntity", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("SkipperModels.Entities.OrderEntity", b =>
                {
                    b.HasOne("SkipperModels.Entities.CustomerEntity", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SkipperModels.Entities.SlipEntity", b =>
                {
                    b.HasOne("SkipperModels.Entities.SlipClassificationEntity", "SlipClassificationEntity")
                        .WithMany()
                        .HasForeignKey("SlipClassificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SlipClassificationEntity");
                });

            modelBuilder.Entity("SkipperModels.Entities.VesselOwnerVesselEntity", b =>
                {
                    b.HasOne("SkipperModels.Entities.VesselEntity", "Vessel")
                        .WithOne()
                        .HasForeignKey("SkipperModels.Entities.VesselOwnerVesselEntity", "VesselId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkipperModels.Entities.VesselOwnerCustomerEntity", "VesselOwnerCustomer")
                        .WithMany("VesselOwnerVessels")
                        .HasForeignKey("VesselOwnerCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vessel");

                    b.Navigation("VesselOwnerCustomer");
                });

            modelBuilder.Entity("SkipperModels.Entities.VesselOwnerCustomerEntity", b =>
                {
                    b.HasOne("SkipperModels.Entities.ContactEntity", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("SkipperModels.Entities.SlipReservationOrderEntity", b =>
                {
                    b.HasOne("SkipperModels.Entities.SlipEntity", "SlipEntity")
                        .WithMany()
                        .HasForeignKey("SlipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkipperModels.Entities.VesselEntity", "VesselEntity")
                        .WithMany()
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SlipEntity");

                    b.Navigation("VesselEntity");
                });

            modelBuilder.Entity("SkipperModels.Entities.BusinessCustomerEntity", b =>
                {
                    b.Navigation("BusinessCustomerContacts");
                });

            modelBuilder.Entity("SkipperModels.Entities.VesselOwnerCustomerEntity", b =>
                {
                    b.Navigation("VesselOwnerVessels");
                });
#pragma warning restore 612, 618
        }
    }
}
